<a href="https://colab.research.google.com/github/irffanhaziq/Data-Science/blob/main/P138120_Week10_DataWrangling_20231213_ORI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 10: Data Wrangling: Clean, Transform, Merge, Reshape**
For details of this Topic (Data Wrangling: Clean, Transform, Merge, Reshape), please refer to the textbook: "Python for Data Analysis" by Wes McKinney

**Chapter 7 & 8**

### **Always starts by importing Pandas and NumPy library - it's like a template :)**

In [ ]:
# Load library
import pandas as pd
import numpy as np

## **Filling In Missing Data**

In [ ]:
# Create a mock data
np.random.seed(12345)
df = pd.DataFrame(np.random.standard_normal((7, 3)))
print(df)
print('\n-------------\n')
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

          0         1         2
0 -0.204708  0.478943 -0.519439
1 -0.555730  1.965781  1.393406
2  0.092908  0.281746  0.769023
3  1.246435  1.007189 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

-------------



0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Filling the NaN with a constant
df.fillna(0.5)

0         1         2
0 -0.204708  0.500000  0.500000
1 -0.555730  0.500000  0.500000
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Display the df output
# Notice that df is still intact
# Function fillna() does not modify the DataFrame by default
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Calling fillna with a different fill value for each column
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.204708  0.500000  0.000000
1 -0.555730  0.500000  0.000000
2  0.092908  0.500000  0.769023
3  1.246435  0.500000 -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Display df output
# Not affecting the df
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.092908       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Challenge: Change cell at (2,0) to 0.37
# This will change the data frame permanently
df.iloc[2,0] = 0.37
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.370000       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Display df output
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.370000       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [ ]:
# Another dummy data
np.random.seed(1234)
df = pd.DataFrame(np.random.standard_normal((6,3)))
df

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.636524  0.015696
3 -2.242685  1.150036  0.991946
4  0.953324 -2.021255 -0.334077
5  0.002118  0.405453  0.289092

In [ ]:
# iloc - integer index
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588       NaN  0.015696
3 -2.242685       NaN  0.991946
4  0.953324       NaN       NaN
5  0.002118       NaN       NaN

In [ ]:
# Fill na forward
df.fillna(method="ffill")

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324 -0.720589  0.991946
5  0.002118 -0.720589  0.991946

In [ ]:
# fill na limit to 2
df.fillna(method="ffill", limit=2)

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324       NaN  0.991946
5  0.002118       NaN  0.991946

In [ ]:
# Another example
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [ ]:
# Data imputation using mean
data.fillna(data.median())

0    1.0
1    3.5
2    3.5
3    3.5
4    7.0
dtype: float64

### **Data Transformation**
Filtering, cleaning, and other transformations

### **Removing Duplicates**

In [ ]:
# Example data with duplicate rows
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

# The ***duplicated() function*** returns a ***Boolean Series*** indicating whether each row is a duplicate to those in an ***earlier row***

In [ ]:
# Detect duplication of data row-wise
# data.duplicated?
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
# Returns a DataFrame with rows where the duplicated array is filtered out
print(data)
print('\n--------------\n')
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

--------------



k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
# Add dummy data
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [ ]:
# Filter duplicates based only on the "k1" column
# By default, keep the first observed value combination
data.drop_duplicates(subset=["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [ ]:
# Passing keep="last" will return the last one
# Remove index 5
print(data)
print('\n------------\n')
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

------------



k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### **Transforming Data Using Mapping**

In [ ]:
# Mock data
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [ ]:
# Mapping of each distinct meat type
meat_to_animal = {
      "bacon": "pig",
      "pulled pork": "pig",
      "pastrami": "cow",
      "corned beef": "cow",
      "honey ham": "pig",
      "nova lox": "salmon"
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [ ]:
# Mapping method
print(data)
print('\n---------\n')
data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

---------



food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### **Replacing Values**

In [ ]:
# Mock data
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [ ]:
# Set -999 values as sentinel value for missing data
# sentinel value -> unique value indicating certain meaning
# Special value that is used to signal the end of a sequence, indicate an error,
# or serve as a termination condition in a program.
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
# Replace multiple sentinel values at once
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [ ]:
# Use a different replacement for each sentinel value
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
# Argument passed as a dictionary
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### **Renaming Axis Indexes**

In [ ]:
# Mock example
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
# Add another column
np.random.seed(1234)
data["five"] = np.random.standard_normal(3)
print(data)

          one  two  three  four      five
Ohio        0    1      2     3  0.471435
Colorado    4    5      6     7 -1.190976
New York    8    9     10    11  1.432707


In [ ]:
# Define a transform() function
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [ ]:
# Rename indexes
# To uppercase
data.index = data.index.map(transform)
data

one  two  three  four      five
OHIO    0    1      2     3 -0.354324
COLO    4    5      6     7 -0.031273
NEW     8    9     10    11  0.078985

Create a transformed version of a dataset ***without modifying the original***, a useful method is ***rename***

In [ ]:
# Rename method
print(data)
print('\n----------\n')
data.rename(index=str.title, columns=str.upper)

      one  two  three  four      five
OHIO    0    1      2     3 -0.354324
COLO    4    5      6     7 -0.031273
NEW     8    9     10    11  0.078985

----------



ONE  TWO  THREE  FOUR      FIVE
Ohio    0    1      2     3 -0.354324
Colo    4    5      6     7 -0.031273
New     8    9     10    11  0.078985

In [ ]:
# Rename can be used in conjunction with a dictionary-like object
data.rename(index={"OHIO": "INDIANA", "NEW ": "New York"},
            columns={"three": "peekaboo", "five": "Seven"})

one  two  peekaboo  four     Seven
INDIANA     0    1         2     3 -0.354324
COLO        4    5         6     7 -0.031273
New York    8    9        10    11  0.078985

In [ ]:
# The original data remains intact
print(data)

      one  two  three  four      five
OHIO    0    1      2     3 -0.354324
COLO    4    5      6     7 -0.031273
NEW     8    9     10    11  0.078985


### **Discretization and Binning**

In [ ]:
# Mock data
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [ ]:
# Divide into bins of 18 to 25, 26 to 35, 36 to 60, and finally 61 and older
# returns a Categorical object
# "(" -> Open parenthesis: Indicates that the value is not included in the interval
# "]" -> Closed square bracket: Indicates that the value is included in the interval
# (18, 25] -> interval includes values greater than 18 and less than or equal to 25.
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

### **Unique pandas categorical object**

In [ ]:
# Codes
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [ ]:
# Categories
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [ ]:
# Accessing single elements
age_categories.categories[3]

Interval(60, 100, closed='right')

In [ ]:
# Count number of each category
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

• **parenthesis** means that the side is open (**exclusive**)

• **square** bracket means it is closed [**inclusive**]

• Example: **[first1, last1)** , the range starts with first1 (and includes it), but ends just before last1

In [ ]:
# Inclusive of left, exclusive (not include) right
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [ ]:
# Exclusive of left, inclusive of right
pd.cut(ages, bins, right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [ ]:
# override the default interval-based bin labeling by passing a list or
# array to the labels option
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
# Some mock data
data = np.random.uniform(size=20)
data

array([0.37744794, 0.01146922, 0.41502885, 0.50524793, 0.34083112,
       0.61391627, 0.24785888, 0.35604357, 0.58724963, 0.30977507,
       0.35281161, 0.05331902, 0.06942953, 0.5748632 , 0.03953196,
       0.2793355 , 0.54401203, 0.98607716, 0.60531113, 0.74948674])

In [ ]:
# Pass an integer number of bins to pandas.cut to compute equal-length bins
# Based on the minimum and maximum values in the data
# Compute equal-length bins
# Precision=2 option limits the decimal precision to two digits
pd.cut(data, 4, precision=2)

[(0.26, 0.5], (0.01, 0.26], (0.26, 0.5], (0.5, 0.74], (0.26, 0.5], ..., (0.26, 0.5], (0.5, 0.74], (0.74, 0.99], (0.5, 0.74], (0.74, 0.99]]
Length: 20
Categories (4, interval[float64, right]): [(0.01, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.99]]

In [ ]:
# Pandas.qcut bins the data based on sample quantiles
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(-0.052, 0.65], (-0.052, 0.65], (-0.052, 0.65], (-3.59, -0.65], (-3.59, -0.65], ..., (-3.59, -0.65], (-0.65, -0.052], (-0.65, -0.052], (-3.59, -0.65], (-3.59, -0.65]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.59, -0.65] < (-0.65, -0.052] < (-0.052, 0.65] <
                                           (0.65, 2.89]]

In [ ]:
# Count each catagory
pd.value_counts(quartiles)

(-3.59, -0.65]     250
(-0.65, -0.052]    250
(-0.052, 0.65]     250
(0.65, 2.89]       250
dtype: int64

In [ ]:
# Another example
# Based on quartiles
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.581, -1.265]    100
(-1.265, -0.052]    400
(-0.052, 1.22]      400
(1.22, 2.891]       100
dtype: int64

### **Detecting and Filtering Outliers**

In [ ]:
# DataFrame with some normally distributed data
# DataFrame of 1000x4
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data

0         1         2         3
0   -0.475385  1.226926 -2.167091  1.223257
1   -0.922365  0.640038 -0.016638  0.323969
2   -0.367627 -0.378298 -0.934919 -0.841889
3   -0.191966 -0.638092 -1.456827  0.588885
4   -0.438901  0.114348 -0.495016 -0.415584
..        ...       ...       ...       ...
995  0.869177  0.313259  0.995544 -0.213028
996  0.765547 -2.179484  0.108088 -1.046411
997  0.890802  0.386905 -0.171756  0.378675
998  0.334922 -1.211243 -1.110466 -0.369606
999 -2.642999  0.112059  0.915320  0.167674

[1000 rows x 4 columns]

In [ ]:
# Explore the dataset in terms of statistics
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.025493    -0.001095     0.027110     0.010880
std       1.020852     0.988471     0.964305     1.001800
min      -2.971552    -3.196714    -2.712683    -2.697663
25%      -0.726363    -0.631996    -0.624679    -0.667268
50%      -0.032514     0.007267     0.038476    -0.057278
75%       0.626783     0.659621     0.649541     0.658694
max       2.970967     3.638738     3.488902     3.867618

In [ ]:
# Find values in one of the columns exceeding 3 in absolute value
# Extracting 3rd column
col = data[2]
col[col.abs() > 3]

403    3.336329
440    3.488902
Name: 2, dtype: float64

In [ ]:
# Select all rows having a value exceeding 3 or –3
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
95  -0.126473  0.643175 -0.241874  3.867618
403  0.148602  0.648972  3.336329 -0.465903
440  2.328852  0.137437  3.488902 -0.545048
649 -0.812975  3.638738 -0.523405  1.012648
986  1.862744 -3.196714 -1.749864  0.406380

In [ ]:
# Cap values outside the interval to minimum –3 and maximum 3
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.025493    -0.001537     0.026285     0.010012
std       1.020852     0.985702     0.961572     0.998827
min      -2.971552    -3.000000    -2.712683    -2.697663
25%      -0.726363    -0.631996    -0.624679    -0.667268
50%      -0.032514     0.007267     0.038476    -0.057278
75%       0.626783     0.659621     0.649541     0.658694
max       2.970967     3.000000     3.000000     3.000000

### **Permutation and Random Sampling**
Permutation - random reordering

In [ ]:
# 2d array of 5x7
df = pd.DataFrame(np.arange(5*7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [ ]:
# Random sampling
sampler = np.random.permutation(5)
sampler

array([2, 3, 0, 1, 4])

In [ ]:
# sampling of the array
df.take(sampler)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [ ]:
# Another way
df.iloc[sampler]

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [ ]:
# Select a permutation of the columns
column_sampler = np.random.permutation(7)
column_sampler

array([0, 1, 4, 5, 2, 3, 6])

In [ ]:
# Sample the colummns
print(df)
print('\n--------\n')
df.take(column_sampler, axis="columns")

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

--------



0   1   4   5   2   3   6
0   0   1   4   5   2   3   6
1   7   8  11  12   9  10  13
2  14  15  18  19  16  17  20
3  21  22  25  26  23  24  27
4  28  29  32  33  30  31  34

In [ ]:
# Select a random subset without replacement
df.sample(n=4)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27

In [ ]:
# Example dataset
choices = pd.Series([5, 7, -1, 6, 4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [ ]:
# Generate a sample with replacement
choices.sample(n=5, replace=False)

2   -1
4    4
1    7
3    6
0    5
dtype: int64

### **Computing Indicator/Dummy Variables**
Converting a categorical variable into a dummy or indicator matrix

In [ ]:
# Example dataframe
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Get dummy dataFrame based on the key
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [ ]:
# Add a prefix
dummies= pd.get_dummies(df["key"], prefix="key")
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [ ]:
# Example data from previous
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Merging of dataset based on the same index number
print(df)
print('\n--------\n')
print(dummies)
print('\n--------\n')
df_with_dummy= df[["data1"]].join(dummies)
df_with_dummy

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

--------

   key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

--------



data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [ ]:
# DataFrame with multiple categories
# movies.dat -> Data can be downlaoded here: https://bit.ly/3VA5elU
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("https://bit.ly/3VA5elU", sep="::", header=None,
                       names=mnames, engine="python")
movies[:6]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller

In [ ]:
# Get data from the genres column
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:6, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1

### **String Manipulation**

In [ ]:
# A comma-separated string can be broken into pieces with split
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [ ]:
# Split is often combined with strip to trim whitespace
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [ ]:
# Substrings could be concatenated together with a
# Two-colon delimiter using addition
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [ ]:
# Another way
"::".join(pieces)

'a::b::guido'

In [ ]:
# Return starting index of the first occurrence of passed substring
# If found in the string
val.index("o")

10

In [ ]:
# Count returns the number of occurrences
val.count(",")

2

### **Regular Expressions**
***regex*** describes a ***pattern to locate*** in the text, which can then be used for many purposes

In [ ]:
# Regex describing one or more whitespace characters -> \s+
# raw string (r"\s+") is often preferred in regular expressions to enhance readability and avoid potential issues with escaping
import re
text = "foo bar\t baz \tqux"
print(text)
print('\n----\n')
re.split(r"\s+", text)

foo bar	 baz 	qux

----



['foo', 'bar', 'baz', 'qux']

In [ ]:
# Compile the regex with re.compile, forming a reusable regex object
# r'\s+' refers to sequence of whitespace
# Avoid unwanted escaping with \ in a regular expression
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [ ]:
# A block of text example
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

# Display text
print(text)

# The pattern to search
# Match a typical email address pattern
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com


In [ ]:
# Extract the information based on the pattern
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

### **String Functions in pandas**
Cleaning up a messy dataset for analysis often requires a lot of string manipulation

In [ ]:
# A column containing strings with missing data
# in dictionary form
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
# Check missing data
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
# Series has array-oriented methods for string operations that skip over
# and propagate NA values
data.str.contains("google")

Dave      True
Steve    False
Rob      False
Wes        NaN
dtype: object

In [ ]:
# String data type
data_as_string = data.astype('string')
data_as_string

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [ ]:
# Boolean data type
data_as_string.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

### **Categorical Data**

In [ ]:
# A mock data
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [ ]:
# Extract distinct values
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [ ]:
# Count
pd.value_counts(values)

apple     6
orange    2
dtype: int64

### **Categorical Extension Type in pandas**
integer-based categorical representation or ***encoding***

In [ ]:
# Some example Series
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [ ]:
# Convert df['fruit'] into categorical; original is a string
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
# Accessing the array attribute
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [ ]:
# Category
c.categories

Index(['apple', 'orange'], dtype='object')

In [ ]:
# codes
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [ ]:
# Mapping between codes and categories
# enumerate() -> is used to iterate over the elements of c.categories along with their index positions
# Returns pairs of index and value.
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

### **Computations with Categoricals**

In [ ]:
# Some mock data
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [ ]:
# Compute a quartile binning and extract some statistics
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [ ]:
# Using labels argument
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [ ]:
# Accessing codes
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [ ]:
# Use groupby to extract summary statistics
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

### **Categorical Methods**

In [ ]:
# Some mock data
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
# cat provides access to categorical methods -> the codes
# returns the integer codes associated with each category in the categorical series
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [ ]:
# Accessing the categories data
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# set_categories method to change new category
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [ ]:
# value_counts for cat_s
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [ ]:
# value_counts for cat_s2
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

### **Hierarchical Indexing**

In [ ]:
# An example
data = pd.Series(np.random.uniform(size=9),
                 index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1,2,3,1,3,1,2,2,3]])
data

a  1    0.622431
   2    0.007569
   3    0.433465
b  1    0.471549
   3    0.883788
c  1    0.942097
   2    0.691469
d  2    0.829183
   3    0.991393
dtype: float64

In [ ]:
# Access the index
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
# Partial indexing
data["b"]

1    0.471549
3    0.883788
dtype: float64

In [ ]:
# Partial indexing
data["b":"c"]

b  1    0.471549
   3    0.883788
c  1    0.942097
   2    0.691469
dtype: float64

In [ ]:
# Partial indexing
# loc[] -> label-based indexing
data.loc[["b", "d"]]

b  1    0.471549
   3    0.883788
d  2    0.829183
   3    0.991393
dtype: float64

In [ ]:
# Partial indexing
print(data)
print('\n---------\n')
data.loc[:, 2]

a  1    0.622431
   2    0.007569
   3    0.433465
b  1    0.471549
   3    0.883788
c  1    0.942097
   2    0.691469
d  2    0.829183
   3    0.991393
dtype: float64

---------



a    0.007569
c    0.691469
d    0.829183
dtype: float64

In [ ]:
# Rearrange this data into a DataFrame using its unstack method
data.unstack()

1         2         3
a  0.622431  0.007569  0.433465
b  0.471549       NaN  0.883788
c  0.942097  0.691469       NaN
d       NaN  0.829183  0.991393

In [ ]:
# Reverse the operation of unstack -> stack
data.unstack().stack()

a  1    0.622431
   2    0.007569
   3    0.433465
b  1    0.471549
   3    0.883788
c  1    0.942097
   2    0.691469
d  2    0.829183
   3    0.991393
dtype: float64

In [ ]:
# Another example
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                     columns=[["Ohio", "Ohio", "Colorado"],
                              ["Green", "Red", "Green"]])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
# add key names
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [ ]:
# Partial indexing
frame["Ohio"]

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### **Reordering and Sorting Levels**

In [ ]:
# Rearrange key
frame.swaplevel("key1", "key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [ ]:
# Another example of rearrange
# level=1 -> the sorting is based on the values in the second level of the index.
print(frame)
print('\n-------\n')
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

-------



state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

### **Summary Statistics by Level**

In [ ]:
# Sum
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [ ]:
# Another example
frame.groupby(level="color", axis="columns").sum()

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

### **Indexing with a DataFrame’s columns**

In [ ]:
# Example dataframe
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                      "c": ["one", "one", "one", "two", "two",
                            "two", "two"],
                      "d":[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [ ]:
# Create a new DataFrame using one or more of its columns as the index
frame2 = frame.set_index(["c", "d"])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [ ]:
# Leave the column intact
frame.set_index(["c", "d"], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [ ]:
# Move the index back to columns
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

### **Combining and Merging Datasets**

### **Database-Style DataFrame Joins**

In [ ]:
# Example datasets
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
# By default - inner join
# keeps only the rows where the "key" values exist in both DataFrames
# Using the same common "feature"
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
# Different column names
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [ ]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [ ]:
# Merge - inner join by default - intersection
# Using specific key
pd.merge(df4, df3, left_on="rkey", right_on="lkey")

rkey  data2 lkey  data1
0    a      0    a      2
1    a      0    a      4
2    a      0    a      5
3    b      1    b      0
4    b      1    b      1
5    b      1    b      6

In [ ]:
# Merge - outer join - union
print(df1)
print('\n----\n')
print(df2)
print('\n----\n')
pd.merge(df1, df2, how="outer")

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

----

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

----



key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    b      5      1
5    b      5      3
6    a      2      0
7    a      2      2
8    a      4      0
9    a      4      2
10   c      3   <NA>
11   d   <NA>      4

In [ ]:
# Merge - outer join - union
print(df3)
print('\n----\n')
print(df4)
print('\n----\n')
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

----

  rkey  data2
0    a      0
1    b      1
2    d      2

----



lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

### **Many-to-many merges**

In [ ]:
# A mock data
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})

In [ ]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [ ]:
# left-join
pd.merge(df1, df2, on="key", how="left")

key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [ ]:
# inner join
# Intersection
pd.merge(df1, df2, how="inner")

key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [ ]:
# merge with multiple keys
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})


In [ ]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [ ]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [ ]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  foo  two     2  <NA>
3  bar  one     3     6
4  bar  two  <NA>     7

### **Concatenating Along an Axis**
***axis=0***; ***moves down*** the column

***axis=1***; ***moves across*** the column to the right

In [ ]:
# an example
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Along the column
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

### **Reshaping and Pivoting**
reshape or pivoting - rearranging tabular data

### ***Reshaping with Hierarchical Indexing***

In [ ]:
# Example data
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                                     name="number"))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Using the stack method to pivot the columns into the rows
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [ ]:
# Rearrange
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Unstack a different level by passing a level number or name
result.unstack(level=0)

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
# Using name
result.unstack(level="state")

state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
# Example
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")
s1

a    0
b    1
c    2
d    3
dtype: Int64

In [ ]:
# example 2
s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")
s2

c    4
d    5
e    6
dtype: Int64

In [ ]:
# Concatenate
data2 = pd.concat([s1, s2], keys=["one", "two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [ ]:
# Unstacking
data2.unstack()

a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [ ]:
# Return original state
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

# **All the best and good luck!!!**









